spring:
  application:
    name: agendamiento-api
  datasource:
    url: jdbc:mysql://localhost:30002/agendifive?useSSL=false&serverTimezone=UTC
    username: carlo
    password: 'Carlos'
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
